[package]
name = "sond-has"
version = "0.1.0"
edition = "2021"
license = "EUPL-1.2"
default-run = "sond-has"

[workspace]
resolver = "2"
members = ["tools/*", "game-dylib"]

[features]
vis_test = ["testing"]
testing = []

[patch.crates-io]
rapier3d = { version = "0.16", path = "../rapier/crates/rapier3d" }
bevy_rapier3d = { version = "0.19.0", path = "../bevy_rapier/bevy_rapier3d" }

[workspace.dependencies.bevy]
version = "0.9.0"
default-features = false
features = [
    "animation",
    "bevy_asset",
#    "bevy_audio", # using kira
    "bevy_gilrs",
    "bevy_scene",
    "bevy_winit",
    "render",
    "png",
    "hdr",
    "vorbis",
    "x11",
    "filesystem_watcher",
]

[workspace.dependencies]
# Mine
enum_components = { package = "sond-bevy-enum-components", path = "../sond-bevy-enum-components" }
particles = { package = "sond-bevy-particles", path = "../sond-bevy-particles" }

# Engine
bevy_rapier3d = { version = "0.19", features = ["debug-render"] }
rapier3d = { version = "0.16", features = ["wasm-bindgen"] }
bevy_kira_audio = "0.13.0"
leafwing-input-manager = "0.7"
leafwing_abilities = "0.3"
bevy_quickmenu = "0.1.1"
bevy_common_assets = { version = "0.4.0", features = ["ron"] }

# Util
bevy_pkv = "0.6.0"
nanorand = { version = "0.7.0", default-features = false, features = ["std", "wyrand", "getrandom"] } # wasm is broken without std and getrandom
noises-and-patterns = "0.1.0"
static_assertions = "1.1.0"
serde = "1"

[dependencies]
# Mine
enum_components = { package = "sond-bevy-enum-components", workspace = true }
particles = { workspace = true }

# Engine
bevy = { workspace = true }
bevy_rapier3d = { workspace = true }
rapier3d = { workspace = true }
bevy_kira_audio = { workspace = true }
leafwing-input-manager = { workspace = true }
leafwing_abilities = { workspace = true }
bevy_quickmenu = { workspace = true }
bevy_common_assets = { workspace = true }

# Util
bevy_pkv = { workspace = true }
nanorand = { workspace = true }
noises-and-patterns = { workspace = true }
static_assertions = { workspace = true }
serde = { workspace = true }


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = "z"
lto = "thin"

[[bin]]
name = "has-vis-tests"
required-features = ["vis_test"]
