name: Pages

on:
  push:
    branches: [release]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: #{{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install -y --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./rs/target/
          key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@beta
        with:
          targets: wasm32-unknown-unknown

      - name: Prepare crate for beta toolchain
        run: |
          rm ./rs/.cargo/config.toml
          rm ./rs/rust-toolchain.toml

      - name: Run tests
        working-directory: ./rs
        run: cargo test --package sond-has-engine --no-default-features --features=testing\
          && cargo test --package sond-has --no-default-features --features=testing,import_assets

      - name: Import assets
        working-directory: ./rs
        run: cargo run --profile test --no-default-features --features=testing,import_assets -- --just-import-assets

      - name: Install Trunk
        uses: jetli/trunk-action@v0.1.0
      - name: Trunk build
        working-directory: ./rs
        run: trunk build --release --public-url "/hack-and-slash/"

      - name: Setup pages
        uses: actions/configure-pages@v2
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./rs/dist
      - name: Deploy Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
