name: Push

on:
  push:
    branches-ignore: [release]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./rs/target/
          key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.toml') }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets:
            wasm32-unknown-unknown,
            x86_64-pc-windows-gnu,
            x86_64-apple-darwin,
            aarch64-linux-android,
            aarch64-apple-ios,

      - name: Prepare crate for stable toolchain
        run: |
          rm ./rs/.cargo/config.toml
          rm ./rs/rust-toolchain.toml

      - name: Linux Build
        working-directory: ./rs
        run: cargo build

      - name: WASM Check
        working-directory: ./rs
        run: cargo check --target wasm32-unknown-unknown

      - name: Windows Check
        working-directory: ./rs
        run: cargo check --target x86_64-pc-windows-gnu

#      - name: MacOS Check
#        working-directory: ./rs
#        run: cargo check --target x86_64-apple-darwin
