name: Push

on:
  push:
    branches-ignore: [release]

env:
  CARGO_TERM_COLOR: always
  CARGO_FEATURE_PURE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false

      - uses: ./.github/actions/setup
        with:
          targets:
            wasm32-unknown-unknown,
            x86_64-pc-windows-gnu,
            x86_64-apple-darwin,

      - name: Linux Build
        working-directory: ./rs
        run: cargo build --profile=desktop --features="vis_test"

      - name: WASM Check
        working-directory: ./rs
        run: cargo check --target wasm32-unknown-unknown

      - name: Windows Check
        working-directory: ./rs
        run: cargo check --profile=desktop --target=x86_64-pc-windows-gnu --all-features

      - name: macOS Check
        working-directory: ./rs
        run: cargo check --profile=desktop --target x86_64-apple-darwin --no-default-features --features="vis_test,import_assets"
